### ISSUE TITLE
Prevent default causing page scrolling lock

### ISSUE THREAD

**Issue by GroundXaero** [marcandre/detect_swipe#10]
Basically if I want a fixed sidebar that you swipe left/right to slide out and back in again and I use the body as the swipe target it prevents you from scrolling the page except when you start the drag from a container element.

If you instead try swiping down or up on an element with content in such as an img or a p tag it prevents default entirely and doesn't let you scroll down.

The way around this for me was to disable the prevent default global setting, but then that introduces some unwelcome left/right page movement when trying to open the sidebar.

Is there a way of preventing default for just up and down swipes with your settings? Or will I have to do so manually?

**Comment by marcandre** [comment]
The thing is, when a swipe starts, I can't know yet if it'll be horizontal, vertical, a bit of both, etc, but I need to take a decision then and there as to preventing it or not. So I don't think it's possible.
