### ISSUE TITLE
"Up" and "down" directions reversed

### ISSUE THREAD

**Issue by Landerson352** [marcandre/detect_swipe#12]
All my devices are showing them flipped. If `dy` is positive (start position is greater than end position), the swipe would be "up", wouldn't it?

https://github.com/marcandre/detect_swipe/blob/master/jquery.detect_swipe.js#L38

**Comment by marcandre** [comment]
Sorry for the delay, I was travelling abroad.

And sorry for the embarassing bug... I only use `left` and `right`!

Fixed, thanks for reporting this.
