### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by cibulka** [marcandre/detect_swipe#14]
Hi, thanks for a simple lib! https://github.com/noelboss/featherlight got me here.

My JS workflow relies on NPM though, so it would help me a lot, if I could find `detect_swipe` there. Would you consider a `npm publish`?

Thanks again, P!

**Comment by marcandre** [comment]
Sure. Done!

**Comment by cibulka** [comment]
One last thing - my browserify setup does not catch correct file on `require('detect_swipe')`. 

I believe that's caused by your `package.json` configuration, its `main` property points to a non-existent file:

```
"main": "jquery/detect_swipe.js"
```

Maybe edit it to ...

```
"main": "jquery.detect_swipe.js"
```

... ? However it's just a nitpicking issue, as I can work with it this way `require('detect_swipe/jquery.detect_swipe.js')` (assuming my `node_modules` are on my Gulp working path). 

Thanks for a quick fix and a nice & simple feature, P!
