### ISSUE TITLE
Problem with pinch / zoom gestures

### ISSUE THREAD

**Issue by loupiote** [marcandre/detect_swipe#16]
The code works well except that it incorrectly detects swipes when the user does a pinch gesture (to zoom-in / zoom out the display). So there should be some code that detects that the use is using a two fingers gesture, and it should not trigger in that case.

I have a photo site the uses your swipe-left/right code to navigate between photos, but it is now basically impossible to zoom on a photo without triggering a swipe, which goes to another photo.

Do you think this is easily fixable?

**Comment by marcandre** [comment]
I didn't realize that multi-touch is supported by browser events, but apparently it is, using `pointer` events: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures
I do not know if `detect_swipe` interacts with them, but if you turn off `$.detectSwipe.preventDefault` it shouldn't interfere.

Good luck

**Comment by loupiote** [comment]
Well, it does interfer.

When you pinch to zoom up, it will trigger swipe events.

You can test on my photo site, that uses your plugin for swipes, e.g. on this page:

https://www.loupiote.com/photos/gooseneck-chico-river-bend-in-the-cordillera-philippines-34814606526.shtml

Or on a phone, just go to www.loupiote.com and click on my face to get to a photo page!

swipe right/left navigates in the photo album. But when you zoom up/down if often triggers a swipe, because some pinching gestures still generate touch events that are caught by the plugin.

This seems to happen more often when you pinch to zoom down while the page is already zoomed to its minimum (i.e. default) size. In that case, the touch events are not captured upfront by Chrome mobile, and they generate unwanted swipe right/left.

I also managed to make it work so that you can still scroll the pages up/down on Firefox mobile, as I explained. I believe it is needed that the handlers return "true" in that case.

On chrome, the up/down touch gestures seems to be captured up-front causing pages to scroll (and zoom), so i believe that it is impossible to get swipe up/down events with the plugin unless your page is set at a "fixed" Y position i.e. not scrollable, regardless of whether you enable /disable default processing (because Chrome processes the events upfront). So $.detectSwipe.preventDefault has no effect at all on the way Chrome processes the touch event upfront, for page scrolling and zooming...
