### ISSUE TITLE
Propagate touch events to underlying layers (under the layer that captures the swipe events) so that buttons and links still work?

### ISSUE THREAD

**Issue by loupiote** [marcandre/detect_swipe#17]
I would like to put a transparent overlay layer over my page, and my page has buttons, links and other clickable objects it it.

I would like swipe gestures to be detected (by the transparent overlay layer), but at the same time, I would like all the touch events to be propagated also to the other layers, so that my buttons and links still work.

Would it be complicated to add an option to do that?

**Comment by marcandre** [comment]
If I understand correctly, you simple want to disable `$.detectSwipe.preventDefault`

**Comment by loupiote** [comment]
Nope, it does not work.

e.g. if i put a text link <a ... > in the underlying layer, events are never sent to it so it is not clickable, that's because once a DOM layer catches mouse / touch events, they are never automatically propagated to underlying layers, even if you do not disable default processing.

It would be necessary to manually send them to underlying layers, and that seems to be really complicated and hard to do right.

So far i have been unable even in simple test cases, and there are many posts on stackoverflow from people having similar issues.
