### ISSUE TITLE
detect_swipe prevents Firefox from scrolling page vertically when vertical swiping

### ISSUE THREAD

**Issue by loupiote** [marcandre/detect_swipe#18]
The plug-in prevents Firefox mobile from scrolling page vertically when vertical swiping.

Interestingly other browsers still do the scrolling (which means of course that vertical swipes are not detected correctly by this plugin).

But in my case-use, i just want to detect left-right swipes, and I want up/down swipe to scroll the page, i.e. the default behavior.

My way to fix this was:

1) remove the call to  e.preventDefault() in onTouchMove().

2) add "return true" at the end of each event handler, so that the default processing occurs.

This fixes the issue with Firefox mobile that was preventing vertical swipes from scrolling the page.

However, I did not try to fix the opposite problem with Chrome, i.e. for people who want to prevent the default page scrolling action while swiping vertically, because in my case I want the default page scroll to occur in that case.

**Comment by marcandre** [comment]
I'm sorry you're having issues with `detect_swipe`.

As mentionned in the doc, you can change the default:
```
detectSwipe.preventDefault // Should touchmove events be prevented?  Defaults to true
```

**Comment by loupiote** [comment]
True, I noticed the way to set preventDefault.

but I believe the handler should return "true" for any default action to run on the event, no?

When there is no value returned by the handler, it defaults to false.

Am I incorrect?
